;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Sep 9 2024
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

TRIGGER_PIN EQU P3.2  ; Define the trigger pin as P3.2

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:	
      MOV A, #10100000b  ; Load the value into accumulator A
      MOV R0, #8         ; Initialize counter to 8 bits

SEND_BIT:
      RL A               ; Rotate accumulator left, MSB to carry
      MOV P1.0, C        ; Move carry bit to P1.0
WAIT_TRIGGER:
      JB TRIGGER_PIN, WAIT_TRIGGER ; Wait until TRIGGER_PIN is high
      JNB TRIGGER_PIN, WAIT_TRIGGER ; Wait until TRIGGER_PIN is low
      DJNZ R0, SEND_BIT  ; Decrement counter and repeat if not zero

Loop:	
      jmp Loop           ; Infinite loop to end the program

;====================================================================
      END